### ISSUE TITLE
Support to bind horizontal layouts

### ISSUE THREAD

**Issue by Tgo1014** [dev-labs-bg/fast-list#1]
First: great lib! I'm using it and it's really practical

Second: Would be great to add support for horizontal recyclerviews

**Comment by radoyankov** [comment]
Doesn't the layout manager method work? Something like 
```.layoutManager(LinearLayoutManager(this, LinearLayoutManager.HORIZONTAL, false))```

**Comment by Tgo1014** [comment]
It does works, but would be nice to had that directly build in, it was just a suggestion. Thanks.
