### ISSUE TITLE
DiffUtil and possible performance update

### ISSUE THREAD

**Issue by brh** [dev-labs-bg/fast-list#12]
In the DiffUtil [code](https://github.com/dev-labs-bg/fast-list/blob/master/fast-list/src/main/java/com/list/rados/fast_list/BaseList.kt#L124-L143)

As suggested by a teammate the areItemsTheSame and the areContentsTheSame should probably be reversed, since the compare closure seems more in line with comparing the contents.  So it will look like this instead
`

            override fun areItemsTheSame(oldItemPosition: Int, newItemPosition: Int): Boolean {
                return items[oldItemPosition] == newList[newItemPosition]
            }

            override fun areContentsTheSame(oldItemPosition: Int, newItemPosition: Int): Boolean {
                return compare(items[oldItemPosition], newList[newItemPosition])
            }`

Or alternatively for more flexibility, you can change the lambda to have an additional param
`compare: (T, T, Boolean)`
where the Boolean lets the method know if this is the contentsTheSame check or not

Final comment, could you be making unnecessary copies of the new list
`items = newList.toMutableList()`
I am not sure if this is needed at all where you can just do
`items = newList`
Or if if has to be mutable
`
if (newList is MutableList)
    items = newList
else
    items = newList.toMutableList()
`

I can send all these changes as a pull request if you like

**Comment by radoyankov** [comment]
Your teammate is right, that does make more sense. Could you make a merge request with that change? You can also include the MutableList check.

**Comment by brh** [comment]
If all ok, please post lib update to maven, jitpack, or whatever.

**Comment by radoyankov** [comment]
yea I'll do that.
