### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by ZaydelEduard** [dev-labs-bg/fast-list#2]
Hey, your library looks nice, thanks for sharing.
But wanna got  more anothers useful features with your library, such as:
- Item click and item chlid click listeners
- Header and footer
- Auto load more
- Item grouping
- Showing a custom view when adapter is empty
- Draggable and swipeable item
etc. 
Cheers!

**Comment by radoyankov** [comment]
Thanks, I'll consider these in the future.
