### ISSUE TITLE
DiffUtil integration

### ISSUE THREAD

**Issue by ATizik** [dev-labs-bg/fast-list#4]
Just wanted to know if you would like to see a pull request with DiffUtil integration?
I think it can be done with observable from kotlin std library.

https://developer.android.com/reference/android/support/v7/util/DiffUtil

**Comment by radoyankov** [comment]
Yes, I'd be happy to review a pull request. Just make sure it's done in a way it's simple to use and understand.
EDIT: As of 1.2 DiffUtils are supported with the "update" function.
