### ISSUE TITLE
Allow for different/custom LayoutManagers

### ISSUE THREAD

**Issue by gtcompscientist** [dev-labs-bg/fast-list#7]
As a user, it would be helpful to be able to pass in a custom `*LayoutManager` to the bind function.

**Comment by radoyankov** [comment]
There is a layoutManager() function which does this.

**Comment by gtcompscientist** [comment]
Doesn't it make far more sense to include this as an override in the setup?

**Comment by radoyankov** [comment]
Default startup takes a linear layout, which is the most commonly used one. If I make it a parameter in the bind function it would have to be optional, and I want to avoid adding optional parameters to the function to keep it simple.

**Comment by gtcompscientist** [comment]
```
fun <T> RecyclerView.bind(items: List<T>,
                          @LayoutRes singleLayout: Int = 0,
                          manager: RecyclerView.LayoutManager = LinearLayoutManager(context),
                          singleBind: (View.(item: T) -> Unit))
        : FastListAdapter<T> {
    layoutManager = manager
    return FastListAdapter(
            items,
            this
    ).map(singleLayout, { true }, singleBind)
}
```
Use:
`recyclerView.bind(items, *LayoutManager()) { ... }`


This seems a lot more intuitive to use than adding a trailing `.layoutManager()` call.

*Also allows you to only have a single "bind" function.
