### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/list/rados/fast_list/FastListViewHolder;

### ISSUE THREAD

**Issue by REBOOTERS** [dev-labs-bg/fast-list#8]
```java
        recyclerView.bind(list, R.layout.recycler_view_item) { item: FragmentItem ->
            name.text = item.name
            path.text = item.path
        }
                .layoutManager(LinearLayoutManager(this))
```

Activity crashed with log "java.lang.NoClassDefFoundError: Failed resolution of: Lcom/list/rados/fast_list/FastListViewHolder;"

used in a Android module library with release 1.2 .

**Comment by radoyankov** [comment]
Could you try and simply copy the library class to your project, instead of getting it with gradle, and see if the problem occurs?

**Comment by REBOOTERS** [comment]
I find out there is only BaseList.kt in fast-list-library ,so I just copy it into my-app-modules.  

```java
import kotlinx.android.extensions.LayoutContainer
```
this import   'extensions'  is red .So BaseList.kt  can not import LayoutContainer Class  . 

so it maybe related with kotlin-plugin-version . I used the newest 1.2.51 . while ,in your project it is 1.2.41.

**Comment by radoyankov** [comment]
I tried it with 1.2.51 and it worked just fine. However, you do need "apply plugin: 'kotlin-android-extensions'"  in your application gradle, for the kotlin extensions. Put that right under "apply plugin: 'kotlin-android'" and your problem should be fixed

**Comment by REBOOTERS** [comment]
en ,problem has been fixed.   but the only way to  use this library  is  with a sub-module in my project , when I use gradle dependency ,it does't work . would you please fix this issue ?

**Comment by RadoslavYankov** [comment]
Yea, you're gonna have to use the class manually if you're using jetpack. I'm not planning on updating it as of right now, because a lot of projects still use the old repositories.
